#!/bin/bash

source .env &&\

rm -rf $SOURCE_DIR &&\
mkdir $SOURCE_DIR &&\

cd $SOURCE_DIR &&\

VERSION='ngx_openresty-1.7.7.1'
URL="http://openresty.org/download/$VERSION.tar.gz"
rm -rf openresty* &&\
curl -o openresty.tar.gz $URL &&\
tar xzvf openresty.tar.gz &&\
mv $VERSION openresty &&\
rm openresty.tar.gz &&\

cd openresty &&\

./configure --prefix=$BUILD_DIR \
  --with-luajit \
  --with-pcre \
  --with-pcre-jit \
  --with-ipv6 \
  --with-libpq=$BUILD_DIR \
  --with-http_postgres_module \
  -j4 &&\

make & make install

#rm  nginx/conf/nginx.conf
#ln -s `pwd`/nginx.conf nginx/conf/nginx.conf
#ls -lah nginx/conf/nginx.conf
